version: 2

# 构建类型：使用 Sphinx 构建器
sphinx:
  configuration: conf.py

# Python 环境设置
python:
  version: 3.10
  install:
    - requirements: requirements.txt

# 构建文档的语言（可选）
build:
  os: ubuntu-22.04

# 如果需要构建 Markdown、PDF 等格式，可扩展配置如下：
# formats:
#   - pdf
#   - epub